export const environment = {
  production: true,
  apiBaseUrl: 'REPLACE_ME_API_BASE_URL',
  mapHubUrl: 'REPLACE_ME_MAP_HUB_URL',
  mapRealtimeEnabled: true,
  mapPollingIntervalMs: 15000,
  mapDisconnectGraceMs: 10000,
  useApiV2: true,
  apiPagedFetchPageSize: 500,
  apiPagedFetchMaxPages: 200,
  logoPayloadMode: 'autoRetryRawBase64' as const,
  mapMaxLocationsPerProject: 20,
  mapMaxTotalRoutes: 3000,
  allowedLogoOrigins: [],
  useMockClientDashboard: false,
  firebase: {
    apiKey: 'REPLACE_ME_FIREBASE_API_KEY',
    authDomain: 'REPLACE_ME_FIREBASE_AUTH_DOMAIN',
    projectId: 'REPLACE_ME_FIREBASE_PROJECT_ID',
    storageBucket: 'REPLACE_ME_FIREBASE_STORAGE_BUCKET',
    messagingSenderId: 'REPLACE_ME_FIREBASE_MESSAGING_SENDER_ID',
    appId: 'REPLACE_ME_FIREBASE_APP_ID',
    measurementId: 'REPLACE_ME_FIREBASE_MEASUREMENT_ID',
  },
};
